CREATE TABLE IF NOT EXISTS "user" (
                    "id" INT GENERATED BY DEFAULT AS IDENTITY,
                    "email" VARCHAR NOT NULL,
                    "login" VARCHAR NOT NULL,
                    "name" VARCHAR NOT NULL,
                    "birthday" DATE,
                    "created_at" TIMESTAMP DEFAULT NOW(),
                    "deleted_at" TIMESTAMP,
                    CONSTRAINT "pk_user" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "film" (
                    "id" INT GENERATED BY DEFAULT AS IDENTITY,
                    "name" VARCHAR NOT NULL,
                    "description" VARCHAR(200),
                    "release_date" DATE,
                    "duration" INT,
                    "mpa_id" INT,
                    "created_at" TIMESTAMP DEFAULT NOW(),
                    "deleted_at" TIMESTAMP,
                    CONSTRAINT "pk_film" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "mpa" (
                    "id" INT GENERATED BY DEFAULT AS IDENTITY,
                    "name" VARCHAR NOT NULL,
                    "description" VARCHAR,
                    CONSTRAINT "pk_mpa" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "genre" (
                    "id" INT GENERATED BY DEFAULT AS IDENTITY,
                    "name" VARCHAR NOT NULL,
                    CONSTRAINT "pk_genre" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "film_genre" (
                    "film_id" INT NOT NULL,
                    "genre_id" INT NOT NULL,
                    CONSTRAINT "pk_film_genre" PRIMARY KEY ("film_id","genre_id")
);

CREATE TABLE IF NOT EXISTS "friendship" (
                    "user_id" INT NOT NULL,
                    "friend_id" INT NOT NULL,
                    "created_at" TIMESTAMP DEFAULT NOW(),
                    "confirmed_at" TIMESTAMP,
                    "deleted_at" TIMESTAMP,
                    CONSTRAINT "pk_friendship" PRIMARY KEY ("user_id","friend_id")
);

CREATE TABLE IF NOT EXISTS "film_user_like" (
                    "film_id" INT NOT NULL,
                    "user_id" INT NOT NULL,
                    "created_at" TIMESTAMP DEFAULT NOW(),
                    "deleted_at" TIMESTAMP,
                    CONSTRAINT "pk_film_user_like" PRIMARY KEY ("film_id","user_id")
);



ALTER TABLE "film" ADD CONSTRAINT IF NOT EXISTS "fk_film_mpa_id" FOREIGN KEY("mpa_id")
    REFERENCES "mpa" ("id");

ALTER TABLE "film_genre" ADD CONSTRAINT IF NOT EXISTS "fk_film_genre_film_id" FOREIGN KEY("film_id")
    REFERENCES "film" ("id");

ALTER TABLE "film_genre" ADD CONSTRAINT IF NOT EXISTS "fk_film_genre_genre_id" FOREIGN KEY("genre_id")
    REFERENCES "genre" ("id");

ALTER TABLE "friendship" ADD CONSTRAINT IF NOT EXISTS "fk_friendship_user_id" FOREIGN KEY("user_id")
    REFERENCES "user" ("id");

ALTER TABLE "friendship" ADD CONSTRAINT IF NOT EXISTS "fk_friendship_friend_id" FOREIGN KEY("friend_id")
    REFERENCES "user" ("id");

ALTER TABLE "film_user_like" ADD CONSTRAINT IF NOT EXISTS "fk_film_user_like_film_id" FOREIGN KEY("film_id")
    REFERENCES "film" ("id");

ALTER TABLE "film_user_like" ADD CONSTRAINT IF NOT EXISTS "fk_film_user_like_user_id" FOREIGN KEY("user_id")
    REFERENCES "user" ("id");


